# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np

height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

# Calculate BMI using the given formula
bmi = weight / (height / 100)**2 * 730

# Print the result
print(bmi)


[168662.0457887  178775.51020408 188256.2983535  197145.0617284
 205479.45205479 213294.37545654 220622.22222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [13]:

import numpy as np

def create_random_matrix(rows, cols, shape='square', dtype=float):
    if shape == 'square':
        size = max(rows, cols)
        matrix = np.random.rand(size, size).astype(dtype)
    elif shape == 'rectangle':
        matrix = np.random.rand(rows, cols).astype(dtype)
    else:
        raise ValueError("Invalid shape type, choose either 'square' or 'rectangle'")
    return matrix
print(create_random_matrix(2,2))
print(create_random_matrix(3,4, shape='rectangle'))



[[0.69951438 0.23304088]
 [0.09563492 0.47997012]]
[[0.37337628 0.68577384 0.05990098 0.53110043]
 [0.04267687 0.39637664 0.2183363  0.80721221]
 [0.88032762 0.63213898 0.86497251 0.3439053 ]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np




In [35]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
import csv
import numpy as np

def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data(r'C:\Users\swapn\Downloads/redsox_2017_hitting.txt')
bs2018 = load_data(r'C:\Users\swapn\Downloads/redsox_2018_hitting.txt')

length = len(bs2018['SLG'])
length = len(bs2017['SLG'])

if (sum(bs2018['SLG']) / length) < (sum(bs2017['SLG']) / length):
    print("SLG is better in 2017")
else:
    print("SLG is better in 2018")    

SLG is better in 2017
